### ISSUE TITLE
Explorer/System freezes after launching installer

### ISSUE THREAD

**Issue by youcangetme** [MindStudioOfficial/livescopestv#3]
**Describe the bug**
Double click the install and then I have to eventually kill the explorer window it was clicked in.

**To Reproduce**
Windows 11, download and double click. 

**Hardware/Software**
- WIndows 11
- nVidia and a RTX3070 

**Additional context**
I have creator's drivers for nVidia

**Comment by MindStudioOfficial** [comment]
Hey there,

First off, I really appreciate you reaching out about the issue with the installer. I know it's not ideal, and I’m here to help sort this out together.

To get a clearer picture of what’s happening, I have a few questions that would really help in understanding the issue better:

1. **Installer Behavior**: When you double-click the installer, does it actually start the installation process, or does it seem like nothing happens at all?
2. **Hanging Detail**: Is it the installer window itself that's hanging, or does it seem like the entire Explorer window becomes unresponsive?
3. **Screen Recording**: If it's not too much trouble, could you provide a short screen recording of what happens when you try to run the installer? It could offer some valuable insights into what's going wrong.

These details will be super helpful for diagnosing the problem. Also, here are a couple of quick things you might try in the meantime, if you haven’t already:

- **Redownload the Installer**: Sometimes files get a bit mixed up during download. A fresh download might just do the trick.
- **Check on Another PC**: If it’s an option, trying the installer on a different PC could help identify if the issue is system-specific.

Thanks a ton for your patience and for helping troubleshoot this. We'll get to the bottom of it and have you up and running in no time!

Looking forward to your response.

**Comment by youcangetme** [comment]
1. Installer Behavior - When I double click there is the warning the application is unsigned and then nothing. The Windows explorer window instantly freezes.
2. Hanging Detail - The explorer instance is hung. When I kill the instance then I can continue on as normal and open new explorer windows.
3. Screen Recording -  yeah, you wouldn't find it helpful. I though it didn't work so I tried to double click it and it didn't even tell me the window wasn't responding. It never pops up the Windows exit slow app menu. You have to hit it several times in the task manager to kill it. 

I am not sure I will download it again. Its not certified by Microsoft so this is going to be a very hard sell to install where its needed.

**Comment by MindStudioOfficial** [comment]
If you see the warning about the application beeing unsigned, you should still be able to click on "More Information" and then "Run Anyway"

I released a new version (1.3.0) that is now self-signed. It is not signed by an official Certificate Authority since I can't afford that right now.

**Comment by youcangetme** [comment]
Well, I was hoping. I would love to have a vector scope etc for my NDI cameras and sources but atlas, it is not to be. This time I had to reboot. It locked everything Windows. Thanks anyways.

**Comment by MindStudioOfficial** [comment]
Do I understand correctly that it worked after a reboot?

**Comment by youcangetme** [comment]
Sorry I was unclear. No, the hang got worse. This time I had to reboot the system.

**Comment by MindStudioOfficial** [comment]
InnoSetup - the installer used to install LiveScopes.tv is not know to cause the explorer or the whole system.
I myself can't think of a way this happens as a result of misconfiguration of the installer itself.

This issue is likely caused by a factor that is out of my control.

Please verify that this Issue only occurs with the LiveScopes.tv installer and not using other installers.

I found this https://answers.microsoft.com/en-us/windows/forum/all/explorer-freezes-when-launching-exe-installer-file/e14f4366-d8de-484f-992b-b71c5e1be2fb forum entry describing a similar issue. You may want to follow the steps provided there to resolve your Issue.

**Comment by youcangetme** [comment]
No, no help. You know what did work? I launched powershell and did `.\livescopestv_setup_v1.3.0.exe` and it installed.

**Comment by youcangetme** [comment]
Ok, it ran for a bit but it crashed out when clicking around. I was showing my son the scopes and some test patterns from the NDI tools and the app sudden took my mouse and was scrolling back and forth across the screen uncontrollably. I couldn't click on anything. Only the windows key would bring up the start menu. I finally had to force shutdown the machine. I uninstalled the app after that. It looked nice but it needs some work. I will keep watch and when you get the issues worked out I will try again.
